TcePCE:
    UNITTEST:
        templateDir:        'OSCARS_DIST/tcePCE/config'
        config.yaml:        'OSCARS_DIST/tcePCE/config/config.HTTP.yaml'
        server-cxf.xml:     'OSCARS_DIST/tcePCE/config/server-cxf-http.xml'
        client-cxf.xml:     'OSCARS_DIST/tcePCE/config/client-cxf-http.xml'
        log4j.properties:   'OSCARS_DIST/tcePCE/config/log4j.DEBUG.properties'
        wsdl:               'OSCARS_DIST/common-soap/src/main/resources/api/pce-0.6.wsdl'

    DEVELOPMENT:
        templateDir:        'OSCARS_HOME/TcePCE/conf/'
        config.yaml:        'OSCARS_HOME/TcePCE/conf/config.HTTP.yaml'
        server-cxf.xml:     'OSCARS_HOME/TcePCE/conf/server-cxf-http.xml'
        client-cxf.xml:     'OSCARS_HOME/TcePCE/conf/client-cxf-http.xml'
        log4j.properties:   'OSCARS_HOME/TcePCE/conf/log4j.MESSAGE.properties'
        wsdl:               'OSCARS_HOME/wsdl/OSCARSService/PCEService-0.6.wsdl'

    SDK:
        templateDir:        'OSCARS_HOME/TcePCE/conf/'
        config.yaml:        'OSCARS_HOME/TcePCE/conf/config.HTTP.yaml'
        server-cxf.xml:     'OSCARS_HOME/TcePCE/conf/server-cxf-http.xml'
        client-cxf.xml:     'OSCARS_HOME/TcePCE/conf/client-cxf-http.xml'
        log4j.properties:   'OSCARS_HOME/TcePCE/conf/log4j.DEBUG.properties'
        wsdl:               'OSCARS_HOME/wsdl/OSCARSService/PCEService-0.6.wsdl'

    PRODUCTION:
        templateDir:        'OSCARS_HOME/TcePCE/conf/'
        config.yaml:        'OSCARS_HOME/TcePCE/conf/config.SSL.yaml'
        server-cxf.xml:     'OSCARS_HOME/TcePCE/conf/server-cxf-ssl.xml'
        client-cxf.xml:     'OSCARS_HOME/TcePCE/conf/client-cxf-ssl.xml'
        log4j.properties:   'OSCARS_HOME/TcePCE/conf/log4j.INFO.properties'
        wsdl:               'OSCARS_HOME/wsdl/OSCARSService/PCEService-0.6.wsdl'

ResourceManagerService:
    UNITTEST:
        config.yaml:        'OSCARS_DIST/resourceManager/config/config.HTTP.yaml'
        wsdl:               'OSCARS_DIST/common-soap/src/main/resources/resourceManager/ResourceManager.wsdl'

    DEVELOPMENT:
        config.yaml:        'OSCARS_HOME/ResourceManagerService/conf/config.HTTP.yaml'
        wsdl:               'OSCARS_HOME/wsdl/ResourceManagerService/ResourceManagerService.wsdl'

    SDK:
        config.yaml:        'OSCARS_HOME/CoordService/conf/config.HTTP.yaml'
        wsdl:               'OSCARS_HOME/wsdl/ResourceManagerService/ResourceManagerService.wsdl'

    PRODUCTION:
        config.yaml:        'OSCARS_HOME/CoordService/conf/config.SSL.yaml'
        wsdl:               'OSCARS_HOME/wsdl/ResourceManagerService/ResourceManagerService.wsdl'

